# Generated by Django 4.0.3 on 2022-09-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0002_graduate_year_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='g_year',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolSystem.graduate_year'),
            preserve_default=False,
        ),
    ]
