# Generated by Django 4.0.3 on 2022-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0004_alter_graduate_year_g_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='g_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
