# Generated by Django 4.0.3 on 2022-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0005_alter_student_g_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
