# Generated by Django 4.0.3 on 2022-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0012_fixed_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_term_fee',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_term_fee',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_term_fee',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
